spring:
  userdatasource:
    username: livepark_admin
    password: admin_pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/livepark_user_db

  globaldatasource:
    username: livepark_user
    password: livepark_pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/livepark_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090

live:
  park:
    app:
      jwtSecret: liveParkSecretKeyliveParkSecretKeyliveParkSecretKeyliveParkSecretKeyliveParkSecretKeylive
      jwtExpirationMs: '86400000'