spring:
  userdatasource:
    username: livepark_admin
    password: admin_pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/livepark_user_db

  globaldatasource:
    username: livepark_user
    password: livepark_pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/livepark_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: livepark08@gmail.com
    password: qypiyjzypcfebzpi # Lucimihai2000
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write-timeout: 5000

server:
  port: 9090

live:
  park:
    app:
      jwtSecret: liveParkSecretKeyliveParkSecretKeyliveParkSecretKeyliveParkSecretKeyliveParkSecretKeylive
      jwtExpirationMs: '86400000'