package ro.license.livepark.entities.car;

public enum CarBrand {
    A_J_MILLER("A.J. Miller"),
    AAC("AAC"),
    AAGLANDER("Aaglander"),
    ABADAL("Abadal"),
    ABARTH("Abarth"),
    ABBOTT_DETROIT("Abbott-Detroit"),
    ABT("ABT"),
    AC_CARS("AC Cars"),
    AC_PROPULSION("AC Propulsion"),
    AC_SCHNITZER("AC Schnitzer"),
    ACADIAN("Acadian"),
    ACCESS_MOTOR("Access Motor"),
    ACME("Acme"),
    ACURA("Acura"),
    ADAM("Adam"),
    ADAMS_FARWELL("Adams-Farwell"),
    ADLER("Adler"),
    ADLY("Adly"),
    AEC("AEC"),
    AEON("Aeon"),
    AEON_MOTOR("Aeon Motor"),
    AERO("Aero"),
    AEV("AEV"),
    AGA("AGA"),
    AION("Aion"),
    AIWAYS("AIWAYS"),
    AIXAM_MEGA("Aixam-Mega"),
    AJAX("Ajax"),
    AJS("AJS"),
    ALAND("Aland"),
    ALBAR("Albar"),
    ALBION("Albion"),
    ALCO("ALCO"),
    ALFA_ROMEO("Alfa Romeo"),
    ALLARD("Allard"),
    ALLDAYS_ONIONS("Alldays & Onions"),
    ALLEN("Allen"),
    ALLEN_IRON_STEEL("Allen Iron & Steel"),
    ALPHEON("Alpheon"),
    ALPINA("ALPINA"),
    ALPINE("Alpine"),
    ALTAS("Altas"),
    ALVIS("Alvis"),
    AM_GENERAL("AM General"),
    AMC("AMC"),
    AMERICAN("American"),
    AMERICAN_AUSTIN("American Austin"),
    AMERICAN_BANTAM("American Bantam"),
    AMERICAN_LAFRANCE("American LaFrance"),
    AMILCAR("Amilcar"),
    AMPHICAR("Amphicar"),
    ANADOL("Anadol"),
    ANASAGASTI("Anasagasti"),
    APOLLO("Apollo"),
    APOLLO_1962_("Apollo (1962)"),
    APPERSON("Apperson"),
    APPLUS_IDIADA("Applus+ IDIADA"),
    ARAB("Arab"),
    ARASH("Arash"),
    ARCFOX("Arcfox"),
    ARCTIC_CAT("Arctic Cat"),
    ARDEN("Arden"),
    ARGYLL("Argyll"),
    ARIEL("Ariel"),
    ARMSTRONG_SIDDELEY("Armstrong Siddeley"),
    ARNOLT("Arnolt"),
    ARO("Aro"),
    ARRINERA("Arrinera"),
    ARTEGA("Artega"),
    AS_DOMŽALE("AS Domžale"),
    ASA("ASA"),
    ASC("ASC"),
    ASCARI("Ascari"),
    ASCOT_PULLIN_MOTORCYCLES("Ascot-Pullin Motorcycles"),
    ASIA("Asia"),
    ASPARK("Aspark"),
    ASPID("Aspid"),
    ASQUITH_MOTORS("Asquith Motors"),
    ASTON_MARTIN("Aston Martin"),
    ASÜNA("Asüna"),
    ATALA("Atala"),
    ATALANTA("Atalanta"),
    ATS("ATS"),
    AUBURN("Auburn"),
    AUDI("Audi"),
    AURUS("Aurus"),
    AUSTIN("Austin"),
    AUSTIN_HEALEY("Austin-Healey"),
    AUSTRO_DAIMLER("Austro-Daimler"),
    AUTO_UNION("Auto Union"),
    AUTOBACS("Autobacs"),
    AUTOBIANCHI("Autobianchi"),
    AUTOCAR("Autocar"),
    AUTOMOBILES_GRÉGOIRE("Automobiles Grégoire"),
    AUTOSTUDI("Autostudi"),
    AUTOZAM("Autozam"),
    AVANTI("Avanti"),
    AVATAR("Avatar"),
    AVIONS_VOISIN("Avions Voisin"),
    AWZ("AWZ"),
    B_ENGINEERING("B Engineering"),
    B_S_A_("B.S.A."),
    BAC("BAC"),
    BAIC("BAIC"),
    BAKER_ELECTRIC("Baker Electric"),
    BALLOT("Ballot"),
    BALTASAR("Baltasar"),
    BALTIJAS_DŽIPS("Baltijas Džips"),
    BANDINI("Bandini"),
    BAOJUN("Baojun"),
    BARKAS("Barkas"),
    BARNARD("Barnard"),
    BAW("BAW"),
    BEAN_CARS("Bean Cars"),
    BEAUMONT("Beaumont"),
    BEDFORD("Bedford"),
    BEIJING("Beijing"),
    BEIJING_JEEP("Beijing Jeep"),
    BELLANGER("Bellanger"),
    BELLIER("Bellier"),
    BELSIZE("Belsize"),
    BELTOISE("Beltoise"),
    BENGALA("Bengala"),
    BENTLEY("Bentley"),
    BENZ("Benz"),
    BERG("Berg"),
    BERKELEY("Berkeley"),
    BERLIET("Berliet"),
    BERTONE("Bertone"),
    BESTUNE("Bestune"),
    BESTURN("Besturn"),
    BIDDLE("Biddle"),
    BIEBER("Bieber"),
    BINZ("BINZ"),
    BIO_AUTO("Bio Auto"),
    BIRD_MOTORCYCLES("Bird Motorcycles"),
    BISU("Bisu"),
    BITTER("Bitter"),
    BIZZARRINI("Bizzarrini"),
    BMC("BMC"),
    BMW("BMW"),
    BODIN("Bodin"),
    BOGDAN("Bogdan"),
    BOLLINGER("Bollinger"),
    BOLWELL("Bolwell"),
    BOND("Bond"),
    BORGWARD("Borgward"),
    BRABHAM("Brabham"),
    BRABUS("Brabus"),
    BRASIER("Brasier"),
    BRASINCA("Brasinca"),
    BRAVIA_MOBIL("Bravia-Mobil"),
    BRENNABOR("Brennabor"),
    BRICKLIN("Bricklin"),
    BRIGGS_DETROITER("Briggs-Detroiter"),
    BRILLIANCE("Brilliance"),
    BRISCOE("Briscoe"),
    BRISTOL("Bristol"),
    BRM("BRM"),
    BROOKE_COMPANY("Brooke & Company"),
    BROOKE_CARS("Brooke Cars"),
    BRP("BRP"),
    BRUSH("Brush"),
    BSA_MOTORCYCLES("BSA Motorcycles"),
    BUCCIALI("Bucciali"),
    BUFORI("Bufori"),
    BUGATTI("Bugatti"),
    BUICK("Buick"),
    BURTON("Burton"),
    BYD("BYD"),
    BYTON("Byton"),
    CABBY("Cabby"),
    CADILLAC("Cadillac"),
    CALCOTT("Calcott"),
    CALLAWAY("Callaway"),
    CALTHORPE("Calthorpe"),
    CAMPAGNA("Campagna"),
    CAN_AM("Can-Am"),
    CANAM("CANAM"),
    CAPARO("Caparo"),
    CARAVANS_INTERNATIONAL("Caravans International"),
    CARBODIES("Carbodies"),
    CARLSSON("Carlsson"),
    CARTERCAR("Cartercar"),
    CARVER("Carver"),
    CASALINI("Casalini"),
    CATERHAM("Caterham"),
    CAV("CAV"),
    CEIRANO("Ceirano"),
    CHALLENGER("Challenger"),
    CHALMERS("Chalmers"),
    CHALMERS_DETROIT("Chalmers-Detroit"),
    CHAMONIX("Chamonix"),
    CHAMPION("Champion"),
    CHANDLER("Chandler"),
    CHANGAN("Changan"),
    CHANGFENG("Changfeng"),
    CHANGHE("Changhe"),
    CHARRON("Charron"),
    CHATENET("Chatenet"),
    CHECKER("Checker"),
    CHENARD_WALCKER("Chenard-Walcker"),
    CHERY("Chery"),
    CHEVROLET("Chevrolet"),
    CHIPIE("Chipie"),
    CHRISTIE("Christie"),
    CHRYSLER("Chrysler"),
    CHTC("CHTC"),
    CHUANL("Chuanl"),
    CIIMO("Ciimo"),
    CISITALIA("Cisitalia"),
    CITROËN("Citroën"),
    CITY_TRANSFORMER("City Transformer"),
    CIZETA("Cizeta"),
    CLEVELAND("Cleveland"),
    CLIPPER("Clipper"),
    CLYNO("Clyno"),
    CLÉMENT_CIE("Clément & Cie"),
    CLÉMENT_BAYARD("Clément-Bayard"),
    CLÉNET("Clénet"),
    CMC("CMC"),
    CMC_CN_("CMC (CN)"),
    COBERA("Cobera"),
    CODA("Coda"),
    COLE("Cole"),
    COLEMAN_MILNE("Coleman Milne"),
    COLUMBIA("Columbia"),
    COMMER("Commer"),
    COMPOUND("Compound"),
    CONCORDE("Concorde"),
    CONNAUGHT("Connaught"),
    CONQUEST_VEHICLES("Conquest Vehicles"),
    COOPER("Cooper"),
    CORADIR("Coradir"),
    CORBELLATI("Corbellati"),
    CORBIN("Corbin"),
    CORD("Cord"),
    CORRE_LA_LICORNE("Corre La Licorne"),
    COSTIN("Costin"),
    COTTIN_DESGOUTTES("Cottin & Desgouttes"),
    COURNIL("Cournil"),
    COVERT("Covert"),
    COVIN("Covin"),
    COWIN("Cowin"),
    CPI_MOTOR("CPI Motor"),
    CRAYFORD("Crayford"),
    CROSLEY("Crosley"),
    CROSSLEY("Crossley"),
    CUNNINGHAM("Cunningham"),
    CUPRA("CUPRA"),
    CUSHMAN("Cushman"),
    CZINGER("Czinger"),
    DACIA("Dacia"),
    DADI("Dadi"),
    DAEWOO("Daewoo"),
    DAF("DAF"),
    DAIHATSU("Daihatsu"),
    DAIMLER("Daimler"),
    DAIMLER_MG("Daimler MG"),
    DALLARA("Dallara"),
    DARRACQ("Darracq"),
    DARTZ("Dartz"),
    DATSUN("Datsun"),
    DAVID_BROWN("David Brown"),
    DAVIS("Davis"),
    DC_DESIGN("DC Design"),
    DE_DIETRICH("De Dietrich"),
    DE_DION_BOUTON("De Dion-Bouton"),
    DE_LA_CHAPELLE("De La Chapelle"),
    DE_TOMASO("De Tomaso"),
    DELAGE("Delage"),
    DELAHAYE("Delahaye"),
    DELIN("Delin"),
    DELLOW("Dellow"),
    DELOREAN("DeLorean"),
    DENZA("Denza"),
    DENZEL("Denzel"),
    DERWAYS("Derways"),
    DESOTO("DeSoto"),
    DETROIT_ELECTRIC("Detroit Electric"),
    DEUS("DEUS"),
    DEVALIET("Devaliet"),
    DEVALLIET("Devalliet"),
    DEVEL("Devel"),
    DEVON("Devon"),
    DFSK("DFSK"),
    DIATTO("Diatto"),
    DINAN("Dinan"),
    DKW("DKW"),
    DODGE("Dodge"),
    DONGFENG("Dongfeng"),
    DONINVEST("Doninvest"),
    DONKERVOORT("Donkervoort"),
    DORCEN("Dorcen"),
    DORRIS("Dorris"),
    DR("DR"),
    DRAGON("Dragon"),
    DRAKO("Drako"),
    DS("DS"),
    DUESENBERG("Duesenberg"),
    DUPONT("duPont"),
    DURANT("Durant"),
    DURYEA("Duryea"),
    DURYEA_POWER("Duryea Power"),
    DÄHLER("dÄHLer"),
    EADON_GREEN("Eadon Green"),
    EAGLE("Eagle"),
    ECOIST("Ecoist"),
    EDAG("EDAG"),
    EDO_COMPETITION("Edo Competition"),
    EDSEL("Edsel"),
    ELDREDGE("Eldredge"),
    ELEMENTAL("Elemental"),
    ELFIN("Elfin"),
    ELIZALDE("Elizalde"),
    ELMORE("Elmore"),
    ELNAGH("Elnagh"),
    ELSTAR_MOTORCYCLES("Elstar Motorcycles"),
    ELVA("Elva"),
    EMGRAND("Emgrand"),
    EMME("Emme"),
    EMW("EMW"),
    ENGLER("Engler"),
    ENGLON("Englon"),
    ENIAK("Eniak"),
    ENRANGER("Enranger"),
    ENVOY("Envoy"),
    EON_MOTORS("Eon Motors"),
    ERL("ERL"),
    ERSKINE("Erskine"),
    ESSEX("Essex"),
    ESTREMA("Estrema"),
    ETERNITI("Eterniti"),
    EUNOS("Eunos"),
    EURA_MOBIL("Eura Mobil"),
    EVERUS("Everus"),
    EVT("EVT"),
    EXAGON("Exagon"),
    EXCALIBUR("Excalibur"),
    FAB_DESIGN("FAB Design"),
    FACEL_VEGA("Facel Vega"),
    FALCON("Falcon"),
    FARADAY_FUTURE("Faraday Future"),
    FARBOUD("Farboud"),
    FARGO("Fargo"),
    FARNOVA("Farnova"),
    FAW("FAW"),
    FEDERAL_COACH("Federal Coach"),
    FELBER("Felber"),
    FELINO("Felino"),
    FENDT("Fendt"),
    FENGSHEN("Fengshen"),
    FENGXING("Fengxing"),
    FENIKSBUS("FENIKSBUS"),
    FERQUI("Ferqui"),
    FERRARI("Ferrari"),
    FIAT("Fiat"),
    FISKER("Fisker"),
    FLINT("Flint"),
    FLYING_MERKEL("Flying Merkel"),
    FN("FN"),
    FODAY("Foday"),
    FORCE("Force"),
    FORD("Ford"),
    FORD_TRUCKS("Ford Trucks"),
    FORD_VAIROGS("Ford-Vairogs"),
    FORDSON("Fordson"),
    FORNASARI("Fornasari"),
    FORVEDA("Forveda"),
    FOTON("Foton"),
    FOX("Fox"),
    FOXTRON("Foxtron"),
    FPV("FPV"),
    FRAM_KING("Fram-King"),
    FRANKIA("Frankia"),
    FRANKLIN("Franklin"),
    FRAZER("Frazer"),
    FRAZER_NASH("Frazer Nash"),
    FREDONIA("Fredonia"),
    FREIGHTLINER("Freightliner"),
    FRISKY("Frisky"),
    FSO("FSO"),
    FULDAMOBIL("Fuldamobil"),
    G_POWER("G-Power"),
    GAC("GAC"),
    GALPIN("Galpin"),
    GAZ("GAZ"),
    GEELY("Geely"),
    GEM("GEM"),
    GEMBALLA("Gemballa"),
    GENERAL_MOTORS("General Motors"),
    GENESIS("Genesis"),
    GENTY("Genty"),
    GEO("Geo"),
    GEOMETRY("Geometry"),
    GFG_STYLE("GFG Style"),
    GHIA("Ghia"),
    GILBERN("Gilbern"),
    GILLET("Gillet"),
    GINETTA("Ginetta"),
    GIOTTILINE("Giottiline"),
    GLAS("Glas"),
    GLEAGLE("Gleagle"),
    GLM("GLM"),
    GMC("GMC"),
    GOBRON_BRILLIÉ("Gobron-Brillié"),
    GOLIATH("Goliath"),
    GONOW("Gonow"),
    GORDON_MURRAY("Gordon Murray"),
    GOUPIL("Goupil"),
    GRAHAM_PAIGE("Graham-Paige"),
    GRANT("Grant"),
    GREAT_WALL("Great Wall"),
    GRECAV("Grecav"),
    GRECH_RV("Grech RV"),
    GREEVES_MOTORCYCLES("Greeves Motorcycles"),
    GRENVILLE("Grenville"),
    GRIFFITH("Griffith"),
    GROUT("Grout"),
    GRUMMAN("Grumman"),
    GSC("GSC"),
    GTA_MOTOR("GTA Motor"),
    GTM("GTM"),
    GUMPERT("Gumpert"),
    GUMPERT_AIWAYS("Gumpert AIWAYS"),
    GURGEL("Gurgel"),
    GUTBROD("Gutbrod"),
    H_E_HALL_CO_("H.E. Hall & co."),
    HAFEI("Hafei"),
    HAIMA("Haima"),
    HAMANN("Hamann"),
    HAMELBOT("Hamelbot"),
    HANOMAG("Hanomag"),
    HANOMAG_HENSCHEL("Hanomag-Henschel"),
    HANSA("Hansa"),
    HANTENG("Hanteng"),
    HARRODS("Harrods"),
    HARTGE("Hartge"),
    HARVARD("Harvard"),
    HAVAL("Haval"),
    HAWTAI("Hawtai"),
    HAYNES_APPERSON("Haynes-Apperson"),
    HEHN_MOBIL("Hehn Mobil"),
    HEINKEL("Heinkel"),
    HENNESSEY("Hennessey"),
    HENNEY("Henney"),
    HENRY_J("Henry J"),
    HENSCHEL("Henschel"),
    HILLMAN("Hillman"),
    HINDUSTAN("Hindustan"),
    HINO("Hino"),
    HISPANO_SUIZA("Hispano Suiza"),
    HM_VEHICLES("HM Vehicles"),
    HOFFMANN("Hoffmann"),
    HOLDEN("Holden"),
    HOLSMAN("Holsman"),
    HOME_CAR("Home-Car"),
    HOMMELL("Hommell"),
    HONDA("Honda"),
    HONGQI("Hongqi"),
    HOPIUM("Hopium"),
    HORCH("Horch"),
    HOTCHKISS("Hotchkiss"),
    HRG("HRG"),
    HSV("HSV"),
    HTT("HTT"),
    HUANGHAI("Huanghai"),
    HUANSU("Huansu"),
    HUASONG("Huasong"),
    HUDSON("Hudson"),
    HUGOS("Hugos"),
    HULME("Hulme"),
    HUMBER("Humber"),
    HUMMER("Hummer"),
    HUPMOBILE("Hupmobile"),
    HURTAN("Hurtan"),
    HURTU("Hurtu"),
    HYBRID_KINETIC("Hybrid Kinetic"),
    HYOSUNG("Hyosung"),
    HYPERION("Hyperion"),
    HYUNDAI("Hyundai"),
    I_DE_A("I.DE.A"),
    IAT("IAT"),
    ICONA("Icona"),
    ICONIQ_MOTORS("Iconiq Motors"),
    IFA("IFA"),
    IFR_AUTOMOTIVE("IFR Automotive"),
    IKA("IKA"),
    IKCO("IKCO"),
    IMPERIAL("Imperial"),
    IMZ("IMZ"),
    INDCAR("Indcar"),
    INDI("INDI"),
    INEOS("Ineos"),
    INFERNO("Inferno"),
    INFINITI("Infiniti"),
    INNOCENTI("Innocenti"),
    INNOCENTI_SCOOTER("Innocenti Scooter"),
    INNOSON("Innoson"),
    INTER_STATE("Inter-State"),
    INTERMECCANICA("Intermeccanica"),
    INTERNATIONAL_HARVESTER("International Harvester"),
    INVACAR("Invacar"),
    INVICTA("Invicta"),
    IRISBUS("Irisbus"),
    IRMÃOS_MOTA("Irmãos Mota"),
    ISDERA("Isdera"),
    ISO("Iso"),
    ISOTTA_FRASCHINI("Isotta Fraschini"),
    ISUZU("Isuzu"),
    ITALDESIGN("Italdesign"),
    IVECO("Iveco"),
    IVECO_BUS("Iveco Bus"),
    IZH("Izh"),
    JAC("JAC"),
    JAGUAR("Jaguar"),
    JANNARELLY("Jannarelly"),
    JAWA("Jawa"),
    JDM("JDM"),
    JEEP("Jeep"),
    JEFFERY("Jeffery"),
    JENSEN("Jensen"),
    JETOUR("Jetour"),
    JETTA("Jetta"),
    JIANGLING("Jiangling"),
    JIANGNAN("Jiangnan"),
    JINBEI("Jinbei"),
    JONWAY("Jonway"),
    JORDAN("Jordan"),
    JOSS("Joss"),
    JOWETT("Jowett"),
    JURASSIC_TRUCK("Jurassic Truck"),
    JÖSSE_CAR("Jösse Car"),
    KAHN_DESIGN("Kahn Design"),
    KAIPAN("Kaipan"),
    KAISER("Kaiser"),
    KALMAR_VERKSTAD("Kalmar Verkstad"),
    KANDI("Kandi"),
    KARMA("Karma"),
    KAVZ("KAvZ"),
    KAWEI("Kawei"),
    KELLISON("Kellison"),
    KEN_OKUYAMA_DESIGN("Ken Okuyama Design"),
    KENTUCKY_CAMP("Kentucky Camp"),
    KEWET("Kewet"),
    KHM("KHM"),
    KIA("Kia"),
    KIEFT("Kieft"),
    KISSEL("Kissel"),
    KLEEMANN("Kleemann"),
    KLEINSCHNITTGER("Kleinschnittger"),
    KNIGHT("Knight"),
    KNOX("Knox"),
    KOENIGSEGG("Koenigsegg"),
    KRASTIN("Krastin"),
    KRUGGER("Krugger"),
    KTM("KTM"),
    KVAB("KVAB"),
    KYBURZ("Kyburz"),
    LADA("Lada"),
    LAFAYETTE("LaFayette"),
    LAFFITE("Laffite"),
    LAGONDA("Lagonda"),
    LAMBORGHINI("Lamborghini"),
    LANCHESTER("Lanchester"),
    LANCIA("Lancia"),
    LAND_ROVER("Land Rover"),
    LANDWIND("Landwind"),
    LARAKI("Laraki"),
    LASALLE("LaSalle"),
    LAURIN_KLEMENT("Laurin & Klement"),
    LDV("LDV"),
    LE_VOYAGEUR("Le Voyageur"),
    LEA_FRANCIS("Lea-Francis"),
    LEAP_MOTOR("Leap Motor"),
    LEECO("LeEco"),
    LENHAM("Lenham"),
    LEOPARD("Leopard"),
    LEVC("LEVC"),
    LEXUS("Lexus"),
    LEYLAND("Leyland"),
    LIFAN("Lifan"),
    LIGHTYEAR("Lightyear"),
    LIGIER("Ligier"),
    LINCOLN("Lincoln"),
    LISTER("Lister"),
    LLOYD("Lloyd"),
    LMC_CARAVAN("LMC Caravan"),
    LOBINI("Lobini"),
    LOCAL_MOTORS("Local Motors"),
    LOCOMOBILE("Locomobile"),
    LOLA("Lola"),
    LOMAX("Lomax"),
    LOMBARDI("Lombardi"),
    LORINSER("Lorinser"),
    LOTUS("Lotus"),
    LTI("LTI"),
    LUAZ("LuAZ"),
    LUCID_MOTORS("Lucid Motors"),
    LUMMA_DESIGN("Lumma Design"),
    LUSITANO("Lusitano"),
    LUVLY("Luvly"),
    LUXGEN("Luxgen"),
    LVCHI("LVCHI"),
    LYNK_CO("Lynk & Co"),
    LYONHEART("Lyonheart"),
    MAGIRUS("Magirus"),
    MAGIRUS_DEUTZ("Magirus-Deutz"),
    MAGNA_STEYR("Magna Steyr"),
    MAGNUM("Magnum"),
    MAHINDRA("Mahindra"),
    MAKO("Mako"),
    MALIBU("Malibu"),
    MALLOCK("Mallock"),
    MAN("MAN"),
    MANHART("MANHART"),
    MANSORY("Mansory"),
    MANTA("Manta"),
    MARAUDER("Marauder"),
    MARCH("March"),
    MARCOPOLO("Marcopolo"),
    MARCOS("Marcos"),
    MARMON("Marmon"),
    MARQUETTE("Marquette"),
    MARUSSIA("Marussia"),
    MARUTI("Maruti"),
    MASERATI("Maserati"),
    MASTRETTA("Mastretta"),
    MATHIS("Mathis"),
    MATRA("Matra"),
    MAXTON("Maxton"),
    MAXUS("Maxus"),
    MAXWELL("Maxwell"),
    MAYBACH("Maybach"),
    MAZDA("Mazda"),
    MAZZANTI("Mazzanti"),
    MCLAREN("McLaren"),
    MCLAUGHLIN("McLaughlin"),
    MCLOUIS("McLouis"),
    MEIER("Meier"),
    MELKUS("Melkus"),
    MERCEDES("Mercedes"),
    MERCEDES_BENZ("Mercedes-Benz"),
    MERCER("Mercer"),
    MERCURY("Mercury"),
    MERKUR("Merkur"),
    MESSERSCHMITT("Messerschmitt"),
    METEOR("Meteor"),
    METZ("Metz"),
    MEV("MEV"),
    MEYRA("Meyra"),
    MG("MG"),
    MICRO("Micro"),
    MICROCAR("Microcar"),
    MIKRUS("Mikrus"),
    MILES("Miles"),
    MINELLI("Minelli"),
    MINERVA("Minerva"),
    MINI("MINI"),
    MITSUBISHI("Mitsubishi"),
    MITSUOKA("Mitsuoka"),
    MIURA("Miura"),
    MMI("MMI"),
    MOBILITY_VENTURES("Mobility Ventures"),
    MOBILIZE("Mobilize"),
    MOBILVETTA("Mobilvetta"),
    MONARCH("Monarch"),
    MONTE_CARLO("Monte Carlo"),
    MONTEVERDI("Monteverdi"),
    MOON("Moon"),
    MORELO("Morelo"),
    MORETTI("Moretti"),
    MORGAN("Morgan"),
    MORRIS("Morris"),
    MOSKVICH("Moskvich"),
    MOSLER("Mosler"),
    MOTOBLOC("Motobloc"),
    MP_LAFER("MP Lafer"),
    MTM("MTM"),
    MTX("MTX"),
    MURTAYA("Murtaya"),
    NAMX("NamX"),
    NANOFLOWCELL("NanoFlowcell"),
    NAPIER("Napier"),
    NARAN("Naran"),
    NASH("Nash"),
    NATIONAL("National"),
    NECKAR("Neckar"),
    NEVS("NEVS"),
    NEXT_E_GO("Next.e.GO"),
    NIESMANN("Niesmann"),
    NILSSON("Nilsson"),
    NIO("NIO"),
    NISSAN("Nissan"),
    NOBE("Nobe"),
    NOBEL("Nobel"),
    NOBLE("Noble"),
    NORDIC("Nordic"),
    NORTHERN("Northern"),
    NOTA("Nota"),
    NOVITEC("Novitec"),
    NSU("NSU"),
    O_S_C_A_("O.S.C.A."),
    OAKLAND("Oakland"),
    OETTINGER("Oettinger"),
    OHTA("Ohta"),
    OLDSMOBILE("Oldsmobile"),
    OLTCIT("Oltcit"),
    OPEL("Opel"),
    ORA("ORA"),
    OSC("OSC"),
    OSI("OSI"),
    OULLIM("Oullim"),
    OVERLAND("Overland"),
    PACKARD("Packard"),
    PAGANI("Pagani"),
    PAIGE("Paige"),
    PAL_V("PAL-V"),
    PANHARD("Panhard"),
    PANOZ("Panoz"),
    PANTHER("Panther"),
    PANTHER_MOTORCYCLES("Panther Motorcycles"),
    PANTORE("Pantore"),
    PAZ("PAZ"),
    PEEL("Peel"),
    PEERLESS("Peerless"),
    PEGASO("Pegaso"),
    PENNINGTON("Pennington"),
    PERODUA("Perodua"),
    PEUGEOT("Peugeot"),
    PGO("PGO"),
    PHELPS_MOTOR_VEHICLE("Phelps Motor Vehicle"),
    PHILLIPS("Phillips"),
    PHOENIX("PhoeniX"),
    PIERCE_ARROW("Pierce-Arrow"),
    PININFARINA("Pininfarina"),
    PIPER_CARS("Piper Cars"),
    PIËCH("Piëch"),
    PK("PK"),
    PLYMOUTH("Plymouth"),
    POGEA_RACING("Pogea Racing"),
    POLAR("Polar"),
    POLARIS("Polaris"),
    POLESTAR("Polestar"),
    POLLMANN("Pollmann"),
    PONTIAC("Pontiac"),
    POPE("Pope"),
    POPE_HARTFORD("Pope-Hartford"),
    POPE_TOLEDO("Pope-Toledo"),
    PORSCHE("Porsche"),
    PRAGA("Praga"),
    PREMIER("Premier"),
    PRINCESS("Princess"),
    PRODRIVE("Prodrive"),
    PROTON("Proton"),
    PUMA("Puma"),
    PURITALIA("Puritalia"),
    PÖSSL("Pössl"),
    QIANTU("Qiantu"),
    QITENG("Qiteng"),
    QOROS("Qoros"),
    QVALE("Qvale"),
    RADICAL("Radical"),
    RAF("RAF"),
    RALLY("Rally"),
    RALT("Ralt"),
    RAM("RAM"),
    RAMBLER("Rambler"),
    RANGER("Ranger"),
    RANZ("Ranz"),
    RAVON("Ravon"),
    REAF("REAF"),
    REGAL("Regal"),
    RELIANT("Reliant"),
    RELY("Rely"),
    RENAULT("Renault"),
    RENAULT_SAMSUNG("Renault Samsung"),
    RENAULT_TRUCKS("Renault Trucks"),
    RENNTECH("RENNtech"),
    REO("REO"),
    REYNARD("Reynard"),
    REZVANI("Rezvani"),
    RGNT("RGNT"),
    RIICH("Riich"),
    RILEY("Riley"),
    RIMAC("Rimac"),
    RIMOR("Rimor"),
    RINSPEED("Rinspeed"),
    RIVERSIMPLE("Riversimple"),
    RIVIAN("Rivian"),
    ROCHET_SCHNEIDER("Rochet-Schneider"),
    ROCKNE("Rockne"),
    RODING("Roding"),
    ROEWE("Roewe"),
    ROLLER_TEAM("Roller Team"),
    ROLLS_ROYCE("Rolls-Royce"),
    ROMETSCH("Rometsch"),
    RONART("Ronart"),
    ROOSEVELT("Roosevelt"),
    ROSSION("Rossion"),
    ROTRAX("Rotrax"),
    ROUSH("Roush"),
    ROVER("Rover"),
    ROYAL("Royal"),
    ROYAL_ENFIELD("Royal Enfield"),
    ROYALE("Royale"),
    ROŠERO("Rošero"),
    RS_MOTORHOMES("RS Motorhomes"),
    RTR("RTR"),
    RUF("RUF"),
    RUGBY("Rugby"),
    RUSSO_BALT("Russo-Balt"),
    S_A_R_A_("S.A.R.A."),
    SAAB("Saab"),
    SABRA("Sabra"),
    SAIC("SAIC"),
    SAIPA("Saipa"),
    SALEEN("Saleen"),
    SALMSON("Salmson"),
    SANDUSKY_AUTOMOBILE("Sandusky Automobile"),
    SANTANA("Santana"),
    SANYOU("Sanyou"),
    SATURN("Saturn"),
    SBARRO("Sbarro"),
    SCION("Scion"),
    SCOTT_MOTORCYCLE("Scott Motorcycle"),
    SCUDERIA_CAMERON_GLICKENHAUS("Scuderia Cameron Glickenhaus"),
    SEAT("SEAT"),
    SEAZ("SeAZ"),
    SEBRING_VANGUARD("Sebring-Vanguard"),
    SECMA("Secma"),
    SECTOR111("Sector111"),
    SELVE("Selve"),
    SENOVA("Senova"),
    SHARE2DRIVE("Share2Drive"),
    SHAYTON("Shayton"),
    SHELBY("Shelby"),
    SHELL("Shell"),
    SHUANGHUAN("Shuanghuan"),
    SIAM_DI_TELLA("Siam Di Tella"),
    SIATA("Siata"),
    SILCCO("SILCCO"),
    SILVERSTONE("Silverstone"),
    SIMCA("Simca"),
    SIMPLEX("Simplex"),
    SIN_CARS("Sin Cars"),
    SINCLAIR("Sinclair"),
    SINGER("Singer"),
    SINOGOLD("Sinogold"),
    SINSKI("Sinski"),
    SKI_DOO("Ski-Doo"),
    SKODA("Skoda"),
    SKYWELL("Skywell"),
    SMA("SMA"),
    SMART("Smart"),
    SMZ("SMZ"),
    SOL("SOL"),
    SOLIFER("Solifer"),
    SONY("Sony"),
    SOUEAST("Soueast"),
    SPECTRE("Spectre"),
    SPEEDWELL("Speedwell"),
    SPYKER("Spyker"),
    SQUIRE("Squire"),
    SRT("SRT"),
    SS_CAR("SS Car"),
    SSANGYONG("SsangYong"),
    SSC("SSC"),
    STANDARD("Standard"),
    STANLEY("Stanley"),
    STAR("Star"),
    STAR_UK_("Star (UK)"),
    STARTECH("STARTECH"),
    STATESMAN("Statesman"),
    STEARNS_KNIGHT("Stearns-Knight"),
    STEVENS_DURYEA("Stevens-Duryea"),
    STEYR("Steyr"),
    STEYR_DAIMLER_PUCH("Steyr-Daimler-Puch"),
    STOEWER("Stoewer"),
    STUDEBAKER("Studebaker"),
    STUTZ("Stutz"),
    SUBARU("Subaru"),
    SUNBEAM("Sunbeam"),
    SUSSITA("Sussita"),
    SUZUKI("Suzuki"),
    SVE("SVE"),
    SVS("SVS"),
    SWALLOW("Swallow"),
    SWEBE("Swebe"),
    SWM("SWM"),
    T_KING("T-King"),
    TAGAZ("TagAZ"),
    TALBOT("Talbot"),
    TARK("TARK"),
    TATA("Tata"),
    TATRA("Tatra"),
    TAURO("Tauro"),
    TAZZARI("Tazzari"),
    TEC("TEC"),
    TECHART("TechArt"),
    TECHRULES("Techrules"),
    TEKAYDINLAR("Tekaydinlar"),
    TERRAPLANE("Terraplane"),
    TESLA("Tesla"),
    THAI_RUNG("Thai Rung"),
    THE_DETROIT_ELETRIC("The Detroit Eletric"),
    THINK("Think"),
    THOMAS("Thomas"),
    THULIN("Thulin"),
    THUNDER_POWER("Thunder Power"),
    TMS("TMS"),
    TMZ("TMZ"),
    TOFAŞ("Tofaş"),
    TOROIDION("Toroidion"),
    TOURING_SUPERLEGGERA("Touring Superleggera"),
    TOYOTA("Toyota"),
    TRABANT("Trabant"),
    TRAMONTANA("Tramontana"),
    TRANSAM_DEPOT("TransAm Depot"),
    TRAUM("Traum"),
    TRI_STAR("Tri-Star"),
    TRIDENT("Trident"),
    TRIGANO("Trigano"),
    TRION("Trion"),
    TRIUMPH("Triumph"),
    TROJAN("Trojan"),
    TROLLER("Troller"),
    TRUMPCHI("Trumpchi"),
    TUCKER("Tucker"),
    TUSHEK("Tushek"),
    TVR("TVR"),
    UAZ("UAZ"),
    UGBEST("UGBEST"),
    ULTIMA("Ultima"),
    UMM("UMM"),
    UNIC("Unic"),
    UNO("UNO"),
    UNVI("UNVI"),
    URALZIS("UralZIS"),
    VABIS("Vabis"),
    VALIANT("Valiant"),
    VAN_DIEMEN("Van Diemen"),
    VANDA_ELECTRICS("Vanda Electrics"),
    VANDEN_PLAS("Vanden Plas"),
    VANDERHALL("Vanderhall"),
    VARSOVIA("Varsovia"),
    VAUXHALL("Vauxhall"),
    VAZ("VAZ"),
    VB_AUTOMOTIVE("VB Automotive"),
    VECTOR_MOTORS("Vector Motors"),
    VEGA("Vega"),
    VEHIXEL("Vehixel"),
    VELOCETTE("Velocette"),
    VENCER("Vencer"),
    VENTO("Vento"),
    VENTURI("Venturi"),
    VENUCIA("Venucia"),
    VERITAS("Veritas"),
    VESPA("Vespa"),
    VEST("Vest"),
    VIKING("Viking"),
    VINCENT_MOTORCYCLES("Vincent Motorcycles"),
    VINFAST("VinFast"),
    VIRITECH("Viritech"),
    VIS("VIS"),
    VLF("VLF"),
    VOLKSWAGEN("Volkswagen"),
    VOLT("VOLT"),
    VOLVO("Volvo"),
    VOLVO_CONSTRUCTION_EQUIPMENT("Volvo Construction Equipment"),
    VORTEX("Vortex"),
    VOYAH("Voyah"),
    VPMZ("VPMZ"),
    VUHL("VUHL"),
    W_MOTORS("W Motors"),
    WANDERER("Wanderer"),
    WARTBURG("Wartburg"),
    WEBER("Weber"),
    WEIWANG("Weiwang"),
    WESTFALIA_MOBIL("Westfalia Mobil"),
    WESTFIELD("Westfield"),
    WEY("Wey"),
    WHIPPET("Whippet"),
    WIESMANN("Wiesmann"),
    WILLYS("Willys"),
    WINNEBAGO("Winnebago"),
    WINTON("Winton"),
    WOLSELEY("Wolseley"),
    WULING("Wuling"),
    XIALI("Xiali"),
    XPENG("Xpeng"),
    YALE("Yale"),
    YAXA("Yaxa"),
    YEMA("Yema"),
    YES_("Yes!"),
    YOUNGMAN_LOTUS("Youngman Lotus"),
    YUGO("Yugo"),
    YULON("Yulon"),
    ZAP("ZAP"),
    ZAROOQ_MOTORS("Zarooq Motors"),
    ZASTAVA("Zastava"),
    ZAZ("ZAZ"),
    ZEEKR("Zeekr"),
    ZENDER("Zender"),
    ZENITH_MOTORCYCLES("Zenith Motorcycles"),
    ZENN("ZENN"),
    ZENOS("Zenos"),
    ZENVO("Zenvo"),
    ZHIDOU("Zhidou"),
    ZHONGYU("Zhongyu"),
    ZIL("ZiL"),
    ZIMMER("Zimmer"),
    ZINORO("Zinoro"),
    ZIS("ZiS"),
    ZNA("ZNA"),
    ZOE("Zoe"),
    ZOTYE("Zotye"),
    ZX("ZX");

    private final String brandName;

    CarBrand(String brandName) {
        this.brandName = brandName;
    }

    public String getBrandName() {
        return brandName;
    }
}
